env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "import/no-unresolved": "off",
  "no-plusplus": "off",
  "class-methods-use-this": "off",
  "no-use-before-define": "warn",
  "no-unused-vars": "warn",
  "jest/no-disabled-tests": "warn",
  "jest/no-focused-tests": "error",
  "jest/no-identical-title": "error",
  "jest/prefer-to-have-length": "warn",
  "jest/valid-expect": "error"
}
plugins:
  - jest
env: {
  "jest/globals": true
}